name: wake-up-dash
version: 0.0.4
summary: Wake up Dash!
description: A simple app to send wake up requests to Wake-on-LAN-enabled devices.

confinement: strict
base: core18
grade: stable

slots:
  wake-up-dash: # adjust accordingly to your app name
    interface: dbus
    bus: session
    name: com.codeglitch.wakeupdash # adjust accordingly to your app name and
    
apps:
  wake-up-dash:
    command: wakeupdash
    extensions: [flutter-master] # Where "master" defines which Flutter channel to use for the build
    plugs:
    - network
    slots:
      - wake-up-dash
parts:
  wake-up-dash:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application
